In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [3]:
df = pd.read_csv('/content/updated_pollution_dataset.csv')
df.head()

Temperature  Humidity  PM2.5  PM10   NO2   SO2    CO  \
0         29.8      59.1    5.2  17.9  18.9   9.2  1.72   
1         28.3      75.6    2.3  12.2  30.8   9.7  1.64   
2         23.1      74.7   26.7  33.8  24.4  12.6  1.63   
3         27.1      39.1    6.1   6.3  13.5   5.3  1.15   
4         26.5      70.7    6.9  16.0  21.9   5.6  1.01   

   Proximity_to_Industrial_Areas  Population_Density Air Quality  
0                            6.3                 319    Moderate  
1                            6.0                 611    Moderate  
2                            5.2                 619    Moderate  
3                           11.1                 551        Good  
4                           12.7                 303        Good

In [7]:
print(df['Air Quality'].unique())

['Moderate' 'Good' 'Hazardous' 'Poor']


In [8]:
air_quality_map = {
    'Hazardous': 0,
    'Poor': 1,
    'Moderate': 2,
    'Good': 3
}

df['Air Quality'] = df['Air Quality'].map(air_quality_map)


In [9]:
df.head()

Temperature  Humidity  PM2.5  PM10   NO2   SO2    CO  \
0         29.8      59.1    5.2  17.9  18.9   9.2  1.72   
1         28.3      75.6    2.3  12.2  30.8   9.7  1.64   
2         23.1      74.7   26.7  33.8  24.4  12.6  1.63   
3         27.1      39.1    6.1   6.3  13.5   5.3  1.15   
4         26.5      70.7    6.9  16.0  21.9   5.6  1.01   

   Proximity_to_Industrial_Areas  Population_Density  Air Quality  
0                            6.3                 319            2  
1                            6.0                 611            2  
2                            5.2                 619            2  
3                           11.1                 551            3  
4                           12.7                 303            3

In [11]:
x = df.drop(columns = ['Air Quality'])
y = df['Air Quality']



In [12]:
x

Temperature  Humidity  PM2.5   PM10   NO2   SO2    CO  \
0            29.8      59.1    5.2   17.9  18.9   9.2  1.72   
1            28.3      75.6    2.3   12.2  30.8   9.7  1.64   
2            23.1      74.7   26.7   33.8  24.4  12.6  1.63   
3            27.1      39.1    6.1    6.3  13.5   5.3  1.15   
4            26.5      70.7    6.9   16.0  21.9   5.6  1.01   
...           ...       ...    ...    ...   ...   ...   ...   
4995         40.6      74.1  116.0  126.7  45.5  25.7  2.11   
4996         28.1      96.9    6.9   25.0  25.3  10.8  1.54   
4997         25.9      78.2   14.2   22.1  34.8   7.8  1.63   
4998         25.3      44.4   21.4   29.0  23.7   5.7  0.89   
4999         24.1      77.9   81.7   94.3  23.2  10.5  1.38   

      Proximity_to_Industrial_Areas  Population_Density  
0                               6.3                 319  
1                               6.0                 611  
2                               5.2                 619  
3                              11.1                 551  
4                              12.7                 303  
...                             ...                 ...  
4995                            2.8                 765  
4996                            5.7                 709  
4997                            9.6                 379  
4998                           11.6                 241  
4999                            8.3                 461  

[5000 rows x 9 columns]

In [13]:
y

0       2
1       2
2       2
3       3
4       3
       ..
4995    0
4996    2
4997    2
4998    3
4999    2
Name: Air Quality, Length: 5000, dtype: int64

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
rf = RandomForestClassifier(random_state=1)
rf.fit(x_train,y_train)

RandomForestClassifier(random_state=1)

In [16]:
y_pred = rf.predict(x_test)

In [17]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.88      0.90       111
           1       0.88      0.90      0.89       186
           2       0.97      0.97      0.97       294
           3       1.00      1.00      1.00       409

    accuracy                           0.96      1000
   macro avg       0.94      0.94      0.94      1000
weighted avg       0.96      0.96      0.96      1000



In [18]:
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy: {accuracy :.2f}")


Accuracy: 0.96


In [19]:
confussion_matrix = confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(confussion_matrix)

Confusion Matrix:
[[ 98  13   0   0]
 [  8 168  10   0]
 [  0   9 284   1]
 [  0   0   0 409]]
